export const ADD_COMMENT_REQUEST="ADD_COMMENT_REQUEST"
export const ADD_COMMENT_SUCCESS="ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_FAIL="ADD_COMMENT_FAIL"


export const GET_COMMENT_REQUEST="GET_COMMENT_REQUEST"
export const GET_COMMENT_SUCCESS="GET_COMMENT_SUCCESS"
export const GET_COMMENT_FAIL="GET_COMMENT_FAIL"



export const GET_COMMENT_COUNT_REQUEST = "GET_COMMENT_COUNT_REQUEST"
export const GET_COMMENT_COUNT_SUCCESS = "GET_COMMENT_COUNT_SUCCESS"
export const GET_COMMENT_COUNT_FAIL = "GET_COMMENT_COUNT_FAIL"

export const UPDATE_COMMENT_REQUEST = "UPDATE_COMMENT_REQUEST"
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS"
export const UPDATE_COMMENT_FAIL = "UPDATE_COMMENT_FAIL"


export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"