export const ADD_POST_REQUEST="ADD_POST_REQUEST"
export const ADD_POST_SUCCESS="ADD_POST_SUCCESS"
export const ADD_POST_FAIL="ADD_POST_FAIL"


export const GET_POST_REQUEST="GET_POST_REQUEST"
export const GET_POST_SUCCESS="GET_POST_SUCCESS"
export const GET_POST_FAIL="GET_POST_FAIL"

export const GET_MY_POST_REQUEST="GET_MY_POST_REQUEST"
export const GET_MY_POST_SUCCESS="GET_MY_POST_SUCCESS"
export const GET_MY_POST_FAIL="GET_MY_POST_FAIL"

export const GET_POST_COUNT_REQUEST = "GET_POST_COUNT_REQUEST"
export const GET_POST_COUNT_SUCCESS = "GET_POST_COUNT_SUCCESS"
export const GET_POST_COUNT_FAIL = "GET_POST_COUNT_FAIL"

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST"
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS"
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL"


export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST"
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"