export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"


export const REGISTER_REQUEST="REGISTER_REQUEST"
export const REGISTER_SUCCESS="REGISTER_SUCCESS"
export const REGISTER_FAIL="REGISTER_FAIL"

export const GET_PROFILE_REQUEST="GET_PROFILE_REQUEST"
export const GET_PROFILE_SUCCESS="GET_PROFILE_SUCCESS"
export const GET_PROFILE_FAIL="GET_PROFILE_FAIL"

export const LOGOUT ="LOGOUT"