export const ADD_CARDEALER_REQUEST="ADD_POST_REQUEST"
export const ADD_CARDEALER_SUCCESS="ADD_CARDEALER_SUCCESS"


export const GET_CARDEALER_REQUEST="GET_CARDEALER_REQUEST"
export const GET_CARDEALER_SUCCESS="GET_CARDEALER_SUCCESS"

export const GET_CARDEALER_COUNT_REQUEST = "GET_CARDEALER_COUNT_REQUEST"
export const GET_CARDEALER_COUNT_SUCCESS = "GET_CARDEALER_COUNT_SUCCESS"

export const UPDATE_CARDEALER_REQUEST="UPDATE_CARDEALER_REQUEST"
export const UPDATE_CARDEALER_SUCCESS="UPDATE_CARDEALER_SUCCESS"